--

SET FOREIGN_KEY_CHECKS = 0;

--

-- ============================================================
-- VIBECRAFT DEMO CONTENT (v2) - Real DCSS assets
-- Gameplay layer 1 on top of v1 (room 100 vibecraft-demo).
-- Upgrades the v1 placeholders to real DCSS/Kenney sprites and
-- adds a second enemy (kobold) with full reward + respawn wiring.
-- Ids reused from v1 (100-104) are REPLACE'd in place; new rows
-- start at 110 to avoid clashes. Safe to run multiple times.
-- Requires: reldens-install-v4.0.0.sql, reldens-basic-config,
-- reldens-sample-data and vibecraft-content-v1.sql applied first.
--
-- DCSS SPRITE NOTE: the dcss-manifest.json (generated by
-- bin/process-dcss.js) was not present when this file was written,
-- so sprite file names below follow the KNOWN DCSS mapping
-- (goblin, kobold, wooden_sword, battle_axe, health_potion,
-- magic_potion, coins, key, crystal_shard, apple, cheese).
-- This SQL ASSUMES the pipeline ran and emitted those files into
-- theme/default/assets/custom/sprites/. If the generated files use
-- a different name pattern, update the asset_file / file columns.
--
-- MAP NOTE: v1 assumed a "respawn-area-monsters" tilelayer existed
-- on the map with spawn tiles 254/255/284/285. That layer is not
-- present in the current vibecraft-demo.json, so the enemies below
-- keep the v1 layer contract and pin the two spawn tiles used
-- (254 goblin, 284 kobold). Both tiles are inside the 30x20 grid
-- and non-colliding (ground-collisions value 0). If the layer is
-- still missing at runtime the respawn plugin will not activate;
-- add the layer to the map to enable it.
-- ============================================================

-- ============================================================
-- ROOM: vibecraft-demo (unchanged from v1, kept for idempotency)
-- ============================================================

REPLACE INTO `rooms` (`id`, `name`, `title`, `map_filename`, `scene_images`, `room_class_key`, `customData`) VALUES
	(100, 'vibecraft-demo', 'Vibecraft Demo', 'vibecraft-demo.json', 'kenney-dungeon.png', NULL, '{"allowGuest":true}');

-- Return points for room 100 (kept from v1, pixel based).
REPLACE INTO `rooms_return_points` (`id`, `room_id`, `direction`, `x`, `y`, `is_default`, `from_room_id`) VALUES
	(100, 100, 'down', 14, 2, 1, NULL),
	(101, 100, 'up', 14, 17, NULL, NULL);

-- ============================================================
-- ITEM GROUPS (ids 100+)
-- Item icons are resolved by the client from the group
-- (lib/inventory/client/plugin.js createGroupBox uses
-- group.files_name). Each group points to a real DCSS sprite so
-- the v1 items (previously group NULL, no icon) render properly.
-- ============================================================

REPLACE INTO `items_group` (`id`, `key`, `label`, `description`, `files_name`, `sort`, `items_limit`, `limit_per_item`) VALUES
	(100, 'vc_weapon', 'Weapon', 'Vibecraft weapons.', 'wooden_sword.png', 1, 0, 0),
	(101, 'vc_potion', 'Potion', 'Vibecraft potions.', 'health_potion.png', 2, 0, 0),
	(102, 'vc_currency', 'Currency', 'Vibecraft currency.', 'coins.png', 3, 0, 0),
	(103, 'vc_misc', 'Misc', 'Vibecraft misc items.', 'crystal_shard.png', 4, 0, 0);

-- ============================================================
-- ITEMS (ids 100-104 REPLACE in place, 110+ added)
-- Item types: 3 single, 4 single_equipment, 5 single_usable.
-- Weapons are boosted via items_item_modifiers, potions heal via
-- operation 1 (increment with maxProperty), same as sample data.
-- ============================================================

REPLACE INTO `items_item` (`id`, `key`, `type`, `group_id`, `label`, `description`, `qty_limit`, `uses_limit`, `useTimeOut`, `execTimeOut`, `customData`) VALUES
	(100, 'wooden_sword', 4, 100, 'Wooden Sword', 'A sturdy wooden sword, perfect for a first adventure.', 0, 0, NULL, NULL, '{"canBeDropped":true}'),
	(101, 'health_potion', 5, 101, 'Health Potion', 'A potion that restores 20 HP.', 0, 1, NULL, NULL, '{"canBeDropped":true,"animationData":{"frameWidth":64,"frameHeight":64,"start":6,"end":11,"repeat":0,"usePlayerPosition":true,"followPlayer":true,"startsOnTarget":true},"removeAfterUse":true}'),
	(102, 'coins', 3, 102, 'Coins', NULL, 0, 1, NULL, NULL, '{"canBeDropped": true}'),
	(103, 'rusty_key', 3, 103, 'Rusty Key', 'An old rusted key, what could it open?', 0, 1, NULL, NULL, '{"canBeDropped":true}'),
	(104, 'crystal_shard', 3, 103, 'Crystal Shard', 'A glowing shard of pure crystal.', 0, 1, NULL, NULL, '{"canBeDropped":true,"nft":true,"mint":"placeholder-mint-address"}'),
	(110, 'battle_axe', 4, 100, 'Battle Axe', 'A heavy axe that hits harder than a wooden sword.', 0, 0, NULL, NULL, '{"canBeDropped":true,"animationData":{"frameWidth":64,"frameHeight":64,"start":6,"end":11,"repeat":0,"destroyOnComplete":true,"usePlayerPosition":true,"followPlayer":true,"startsOnTarget":true}}'),
	(111, 'magic_potion', 5, 101, 'Magic Potion', 'A potion that restores 20 MP.', 0, 1, NULL, NULL, '{"canBeDropped":true,"animationData":{"frameWidth":64,"frameHeight":64,"start":6,"end":11,"repeat":0,"usePlayerPosition":true,"followPlayer":true,"startsOnTarget":true},"removeAfterUse":true}'),
	(112, 'apple', 5, 103, 'Apple', 'A fresh apple that restores 5 HP.', 0, 1, NULL, NULL, '{"canBeDropped":true,"animationData":{"frameWidth":64,"frameHeight":64,"start":6,"end":11,"repeat":0,"usePlayerPosition":true,"followPlayer":true,"startsOnTarget":true},"removeAfterUse":true}'),
	(113, 'cheese', 5, 103, 'Cheese', 'A tasty cheese that restores 5 HP and boosts attack.', 0, 1, NULL, NULL, '{"canBeDropped":true,"animationData":{"frameWidth":64,"frameHeight":64,"start":6,"end":11,"repeat":0,"usePlayerPosition":true,"followPlayer":true,"startsOnTarget":true},"removeAfterUse":true}');

-- Modifiers: operation 1 = increment (with maxProperty for heals),
-- operation 5 = increment percentage (weapons, same as sample axe).
REPLACE INTO `items_item_modifiers` (`id`, `item_id`, `key`, `property_key`, `operation`, `value`, `maxProperty`) VALUES
	(100, 100, 'atk', 'stats/atk', 5, '5', NULL),
	(101, 101, 'health_potion', 'stats/hp', 1, '20', 'statsBase/hp'),
	(110, 110, 'atk', 'stats/atk', 5, '8', NULL),
	(111, 111, 'magic_potion', 'stats/mp', 1, '20', 'statsBase/mp'),
	(112, 112, 'apple', 'stats/hp', 1, '5', 'statsBase/hp'),
	(113, 113, 'cheese_hp', 'stats/hp', 1, '5', 'statsBase/hp'),
	(114, 113, 'cheese_atk', 'stats/atk', 5, '1', NULL);

-- Drop bodies: each item renders as its real DCSS sprite when
-- dropped (drops_animations, sample pattern). Coins uses coins.png.
REPLACE INTO `drops_animations` (`id`, `item_id`, `asset_type`, `asset_key`, `file`, `extra_params`) VALUES
	(100, 100, NULL, 'wooden_sword', 'wooden_sword.png', '{"start":0,"end":0,"repeat":-1,"frameWidth":32,"frameHeight":32,"depthByPlayer":"above"}'),
	(101, 101, NULL, 'health_potion', 'health_potion.png', '{"start":0,"end":0,"repeat":-1,"frameWidth":32,"frameHeight":32,"depthByPlayer":"above"}'),
	(102, 102, NULL, 'coins', 'coins.png', '{"start":0,"end":0,"repeat":-1,"frameWidth":32,"frameHeight":32,"depthByPlayer":"above"}'),
	(103, 103, NULL, 'rusty_key', 'key.png', '{"start":0,"end":0,"repeat":-1,"frameWidth":32,"frameHeight":32,"depthByPlayer":"above"}'),
	(104, 104, NULL, 'crystal_shard', 'crystal_shard.png', '{"start":0,"end":0,"repeat":-1,"frameWidth":32,"frameHeight":32,"depthByPlayer":"above"}'),
	(105, 110, NULL, 'battle_axe', 'battle_axe.png', '{"start":0,"end":0,"repeat":-1,"frameWidth":32,"frameHeight":32,"depthByPlayer":"above"}'),
	(106, 111, NULL, 'magic_potion', 'magic_potion.png', '{"start":0,"end":0,"repeat":-1,"frameWidth":32,"frameHeight":32,"depthByPlayer":"above"}'),
	(107, 112, NULL, 'apple', 'apple.png', '{"start":0,"end":0,"repeat":-1,"frameWidth":32,"frameHeight":32,"depthByPlayer":"above"}'),
	(108, 113, NULL, 'cheese', 'cheese.png', '{"start":0,"end":0,"repeat":-1,"frameWidth":32,"frameHeight":32,"depthByPlayer":"above"}');

-- ============================================================
-- OBJECTS (ids 100-103 REPLACE in place, 104 added, room 100)
-- class_type: 3 npc, 5 trader (merchant, same as sample npc_3),
-- 7 multiple (enemy via private_params childObjectType 4),
-- 2 animation (door, decorative, no change-point link).
-- NPCs and the door use the fully floored "ground" layer.
-- Enemies are pinned to the two spawn tiles of the
-- "respawn-area-monsters" layer (254 goblin, 284 kobold).
-- ============================================================

REPLACE INTO `objects` (`id`, `room_id`, `layer_name`, `tile_index`, `class_type`, `object_class_key`, `client_key`, `title`, `private_params`, `client_params`, `enabled`) VALUES
	(100, 100, 'ground', 374, 3, 'vibecraft_guide', 'guide_npc_1', 'Vibecraft Guide', '{"runOnAction":true,"playerVisible":true,"sendInvalidOptionMessage":true}', '{"content":"Welcome to Vibecraft! I am the guide of this realm. Explore the dungeon, defeat the goblins and collect their treasures.","options":{"1":{"label":"Who are you?","value":1},"2":{"label":"How do I fight?","value":2},"3":{"label":"Goodbye.","value":3}},"ui":true}', 1),
	(101, 100, 'ground', 434, 5, 'vibecraft_merchant', 'merchant_1', 'Merchant Grendy', '{"runOnAction":true,"playerVisible":true,"sendInvalidOptionMessage":true}', '{"content":"Hi there! What would you like to do?","options":{"buy":{"label":"Buy","value":"buy"},"sell":{"label":"Sell","value":"sell"}}}', 1),
	(102, 100, 'respawn-area-monsters', 254, 7, 'vibecraft_goblin', 'enemy_goblin_1', 'Goblin', '{"shouldRespawn":true,"childObjectType":4,"isAggressive":true}', '{"autoStart":true}', 1),
	(103, 100, 'ground', 405, 2, 'vibecraft_door', 'door_dungeon_1', 'Dungeon Door', '{"runOnHit":true,"roomVisible":true,"yFix":6}', '{"positionFix":{"y":-18},"frameStart":0,"frameEnd":3,"repeat":0,"hideOnComplete":false,"autoStart":false,"restartTime":2000}', 1),
	(104, 100, 'respawn-area-monsters', 284, 7, 'vibecraft_kobold', 'enemy_kobold_1', 'Kobold', '{"shouldRespawn":true,"childObjectType":4,"isAggressive":true}', '{"autoStart":true}', 1);

-- Object assets: real DCSS/Kenney sprites, 32x32 frames except the
-- door (32x58, same as sample door). Files assumed generated by the
-- DCSS pipeline (see header note).
REPLACE INTO `objects_assets` (`object_asset_id`, `object_id`, `asset_type`, `asset_key`, `asset_file`, `extra_params`) VALUES
	(100, 100, 'spritesheet', 'guide_npc_1', 'hero-2.png', '{"frameWidth":32,"frameHeight":32}'),
	(101, 101, 'spritesheet', 'merchant_1', 'hero-4.png', '{"frameWidth":32,"frameHeight":32}'),
	(102, 102, 'spritesheet', 'enemy_goblin_1', 'goblin.png', '{"frameWidth":32,"frameHeight":32}'),
	(103, 103, 'spritesheet', 'door_dungeon_1', 'door-a-x2.png', '{"frameWidth":32,"frameHeight":58}'),
	(104, 104, 'spritesheet', 'enemy_kobold_1', 'kobold.png', '{"frameWidth":32,"frameHeight":32}');

-- Enemy animations (sample format: {layer_name}_{object_id}_{dir}).
REPLACE INTO `objects_animations` (`id`, `object_id`, `animationKey`, `animationData`) VALUES
	(100, 102, 'respawn-area-monsters_102_right', '{"start":6,"end":8}'),
	(101, 102, 'respawn-area-monsters_102_down', '{"start":0,"end":2}'),
	(102, 102, 'respawn-area-monsters_102_left', '{"start":3,"end":5}'),
	(103, 102, 'respawn-area-monsters_102_up', '{"start":9,"end":11}'),
	(104, 104, 'respawn-area-monsters_104_right', '{"start":6,"end":8}'),
	(105, 104, 'respawn-area-monsters_104_down', '{"start":0,"end":2}'),
	(106, 104, 'respawn-area-monsters_104_left', '{"start":3,"end":5}'),
	(107, 104, 'respawn-area-monsters_104_up', '{"start":9,"end":11}');

-- Enemy stats (sample pattern: all 10 stats set to 50).
REPLACE INTO `objects_stats` (`id`, `object_id`, `stat_id`, `base_value`, `value`) VALUES
	(100, 102, 1, 50, 50),
	(101, 102, 2, 50, 50),
	(102, 102, 3, 50, 50),
	(103, 102, 4, 50, 50),
	(104, 102, 5, 50, 50),
	(105, 102, 6, 50, 50),
	(106, 102, 7, 50, 50),
	(107, 102, 8, 50, 50),
	(108, 102, 9, 50, 50),
	(109, 102, 10, 50, 50),
	(110, 104, 1, 50, 50),
	(111, 104, 2, 50, 50),
	(112, 104, 3, 50, 50),
	(113, 104, 4, 50, 50),
	(114, 104, 5, 50, 50),
	(115, 104, 6, 50, 50),
	(116, 104, 7, 50, 50),
	(117, 104, 8, 50, 50),
	(118, 104, 9, 50, 50),
	(119, 104, 10, 50, 50);

-- Enemy combat skill (sample: skill 1 attackBullet targeting
-- players, target_options id 2 = player).
REPLACE INTO `objects_skills` (`id`, `object_id`, `skill_id`, `target_id`) VALUES
	(100, 102, 1, 2),
	(101, 104, 1, 2);

-- Enemy respawn (layer matches the map layer, 1 instance each).
REPLACE INTO `respawn` (`id`, `object_id`, `respawn_time`, `instances_limit`, `layer`) VALUES
	(100, 102, 30000, 1, 'respawn-area-monsters'),
	(101, 104, 30000, 1, 'respawn-area-monsters');

-- Enemy rewards: coins only (drop animation defined above),
-- goblin 3 coins + 10 exp, kobold 2 coins + 15 exp.
REPLACE INTO `rewards` (`id`, `object_id`, `item_id`, `modifier_id`, `experience`, `drop_rate`, `drop_quantity`, `is_unique`, `was_given`, `has_drop_body`) VALUES
	(100, 102, 102, NULL, 10, 100, 3, 0, 0, 1),
	(101, 104, 102, NULL, 15, 100, 2, 0, 0, 1);

--

SET FOREIGN_KEY_CHECKS = 1;

--
